# Generated by Django 2.2.4 on 2021-07-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dpto', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero_calle', models.IntegerField()),
                ('comuna', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
