# Generated by Django 2.2.4 on 2021-07-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
