$(document).ready(function(){
    $("#b0").hide()
    $("#b1").hide()
    $("#b2").hide()
    $("#b3").hide()
    $("#b4").hide()
    $("#a0").click(function(){
        $(this).hide();
        $('#b0').show();
    });
    $("#b0").click(function(){
        $(this).hide();
        $('#a0').show();
    });
    $("#a1").click(function(){
        $(this).hide();
        $('#b1').show();
    });
    $("#b1").click(function(){
        $(this).hide();
        $('#a1').show();
    });
    $("#a2").click(function(){
        $(this).hide();
        $('#b2').show();
    });
    $("#b2").click(function(){
        $(this).hide();
        $('#a2').show();
    });
    $("#a3").click(function(){
        $(this).hide();
        $('#b3').show();
    });
    $("#b3").click(function(){
        $(this).hide();
        $('#a3').show();
    });
    $("#a4").click(function(){
        $(this).hide();
        $('#b4').show();
    });
    $("#b4").click(function(){
        $(this).hide();
        $('#a4').show();
    });
});